version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout
     # build the application image
    - run: |
        docker build -t project .
    
    # login to docker
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    # deploy the image
    - run: |
        if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
          DOCKER_BRANCH="latest"
        else
          DOCKER_BRANCH="${CIRCLE_BRANCH}"
        fi
        DOCKER_TAG="igormaka/swift-libpostal:$DOCKER_BRANCH"
        docker tag project $DOCKER_TAG
        docker push $DOCKER_TAG