version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout
     # build the application image
    - run: docker build -t igormaka/swift-postal:$CIRCLE_BRANCH .
    
    # login to docker
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    # deploy the image
    - run: docker push igormaka/swift-postal:$CIRCLE_BRANCH